### ISSUE TITLE
Plasma Theme: Lux / El icono de Bluetooth se ve raro

### ISSUE THREAD

**Issue by x11tete11x** [mcder3/The-Lucis-Project#1]
El icono del bluetooth se ve como "pixelado" en el centro, les muestro para ver que les parece

![screenshot_20170216_143642](https://cloud.githubusercontent.com/assets/2127236/23033085/9686129e-f455-11e6-8348-95f95850739a.png)

**Comment by mcder3** [comment]
Es agrede tete jejeje

http://imgur.com/5GgSmS8

**Comment by x11tete11x** [comment]
Ahhh xD, entonces cierro el issue

PD: Me encantó el tema plasma  :D

**Comment by mcder3** [comment]
Lo que tratamos de hacer es que este tema (espero que se añadan mas elementos en un futuro) sea mas comunitario. escuchar las sugerencias de los demás para lograr algo bueno e interesante :-)

**Comment by fabianalexisinostroza** [comment]
la explicación de por qué está hecho es la siguiente. Plasma no se lleva muy bien con las diagonales ni con los círculos en tamaños menores a 16px, en el caso del icono de bluetooth, la "B" está en un tamaño menor a esos 16 px, lo cual al hacer las diagonales le quitaría nitidez al icono en el centro. De hecho por lo mismo los iconos del systray intentan ser lo más rectos posibles de poder hacerse
