### ISSUE TITLE
Plasma Theme: Lux / Pequeñas lineas blancas

### ISSUE THREAD

**Issue by x11tete11x** [mcder3/The-Lucis-Project#2]
No se si está hecho así pero hay pequeñas lineas blancas en el scroll de por ejemplo el menu de plasma
Mi sugerencia es que no estén dichas lineas

![screenshot_20170216_144056](https://cloud.githubusercontent.com/assets/2127236/23033287/42579142-f456-11e6-88f6-20f3cd890937.png)

**Comment by mcder3** [comment]
Si se quitan esas lineas salen afectados muchos elementos por desgracia, pero se podría hacer mas tenue para que no se viera tan sobre expuesta.
