### ISSUE TITLE
Plasma Theme: Noc / Application Menu widget search overlap

### ISSUE THREAD

**Issue by Jazqa** [mcder3/The-Lucis-Project#3]
First of all, thanks for the great theme! Not too many decent Plasma themes available. Anyways, I've spotted a little issue with the Application Menu widget and decided I'd report it here.

![screenshot_20170914_005328](https://user-images.githubusercontent.com/18004783/30402716-5d406e26-98e7-11e7-8fca-850d6d17252b.png)

**Comment by mcder3** [comment]
thank you very much for reporting the error, I will try to solve the problem as soon as possible :-)

**Comment by mcder3** [comment]
It is apparently an error in the design of the plasmoid, as the text box is transparent can not hide the text "Applications"
