### ISSUE TITLE
The indicator for multiple instances hides the icon.

### ISSUE THREAD

**Issue by ghost** [mcder3/The-Lucis-Project#4]
Hi,
really nice theme!

![screenshot_20170915_095012](https://user-images.githubusercontent.com/1175098/30460681-adf7519e-99fb-11e7-99ac-1c577123ad17.png)

My only issue is, as you can see from the screen-shot, that the indicator (or whatever it is called) for multiple instances basically hides the icon for the app. 

Could you improve that? In most theme, that indicator is a much smaller dot.

Cheers.

**Comment by mcder3** [comment]
Thank you very much for warning about the error, I think that already solves that problem.

![task-error](https://user-images.githubusercontent.com/1154298/30461942-66d30f00-997f-11e7-8751-129006da6d36.png)

The change will take effect until version 1.3.0

**Comment by ghost** [comment]
Cool! Much better! Keep the good work.
 I also noticed that one icon in the network monitor also looks out of place...

![screenshot_20170915_123302](https://user-images.githubusercontent.com/1175098/30463944-0e8fa112-9a12-11e7-81a7-725e089bdb0e.png)

It looks like coming from the ubuntu world...

Cheers.

**Comment by mcder3** [comment]
Apparently, I have no problems. I do not know if it will be for the distro or the plasma version.

![3](https://user-images.githubusercontent.com/1154298/30485305-336448c6-99ea-11e7-9466-ed0ae95e57b5.png)

![2](https://user-images.githubusercontent.com/1154298/30484262-1f14015c-99e7-11e7-8a3e-d59e10e150de.png)


In my case I use archlinux + plasma 5.10.5
