### ISSUE TITLE
GTK & QT completo

### ISSUE THREAD

**Issue by CeCallejas** [mcder3/The-Lucis-Project#5]
Hola, excelente arte :). 

Mi duda es si se tiene planeado crear un tema GTK para complementar la línea de diseño y si no es el caso, ¿que tema recomienda para complematar el estilo del lado de GTK?

**Comment by mcder3** [comment]
Yo prácticamente uso Breeze y pues no diseño temas para GTK por la falta de tiempo... pues la verdad no sabría decirte, ya que no uso entornos basados en GNOME... Te pido disculpas por no poder ayudarte :-(

**Comment by CeCallejas** [comment]
Veré si puedo ayudar en hacer algo para GTK para complementar, si funciona me comunico contigo para que veas si te convence :)

**Comment by mcder3** [comment]
Ok dale, cuando tengas algo me lo mandas :-)

**Comment by CeCallejas** [comment]
Hola nuevamente, te quería preguntar si puedes hacer un esquema de colores para konsole, si no tienes tiempo yo puedo hacerlo solo necesitaría la paleta de colores de noc, dejo mi contacto callejasmartinez12@gmail.com

**Comment by CeCallejas** [comment]
Pase diseñando un esquema, al final copie el tema de dracula(https://draculatheme.com/konsole/), los colores se los adapte y cambie el orden de algunos colores, el verde lo saque del tema monokai y también lo adapte al color de fondo el cual es el color negro de noc de las ventanas.

![screenshot_20170924_190858](https://user-images.githubusercontent.com/13605392/30788806-eaa63ace-a15d-11e7-97fb-2b2af5330991.png)
![screenshot_20170924_190221](https://user-images.githubusercontent.com/13605392/30788811-ef44f548-a15d-11e7-8b96-3e47bc84de28.png)
![screenshot_20170924_190551](https://user-images.githubusercontent.com/13605392/30788813-f15665a6-a15d-11e7-8686-16989137d590.png)
![screenshot_20170924_190709](https://user-images.githubusercontent.com/13605392/30788814-f384eb40-a15d-11e7-8aaa-7e2d5eef6025.png)
![screenshot_20170924_190756](https://user-images.githubusercontent.com/13605392/30788815-f5072a3c-a15d-11e7-9dc4-10efa52ab3eb.png)

**Comment by mcder3** [comment]
Enserio te agradezco mucho por el querer aportar :-) , pero la visión de "The Lucis Proyect" es crear elementos desde cero para mantener la originalidad del trabajo.

**Comment by CeCallejas** [comment]
Ok, veré como puedo ayudar entonces :)

**Comment by CeCallejas** [comment]
Si puedes compartir el esquema de colores de tu theme puedo ayudar
