### ISSUE TITLE
Can only install 1 of the 3 themes

### ISSUE THREAD

**Issue by ghost** [mcder3/The-Lucis-Project#6]
Hi, 
as I really liked Lux, I wanted to see how the other themes look like. But as they are all in the same entry in the plasma add on installer, I can only have one at the time in the system... Maybe you have to create 1 entry for each.

Good look! And nice job!

PS: Saludos de este argentino que ahora vive en Sydney!

**Comment by mcder3** [comment]
Hola, mira la verdad que se podría pero seria mantener 3 hilos que al final lo vuelve un poco tedioso, lo que puedes hacer es descargarlos e instalarlos por medio de [github](https://github.com/mcder3/The-Lucis-Project/releases) pero trata de descargar una vez por medio de opendesktop para que cuente como descarga sino es mucha molestia :-)

**Comment by CeCallejas** [comment]
mcder3 y si agregas los pasos para instalarlo en el README?

**Comment by mcder3** [comment]
La cuestión es que el repo cubrirá mas elementos (hace poco subi Noc para Yakuake) y pues no es tan difícil. solo descarga lo que esta en repo y copia todo lo de la carpeta "Plasma Themes" a la carpeta /home/usuario/.local/share/plasma/desktoptheme/ de ahí te vas a preferencias y veras que ya están instalados :P
