### ISSUE TITLE
Ayuda con instalar el tema para yakuake

### ISSUE THREAD

**Issue by DevDorrejo** [mcder3/The-Lucis-Project#7]
Hola,

1ro: Quiero agradecer el trabajo que haces en crear un tema hermoso y práctico para los usuarios de KDE.

2do: Te agradezco crear un tema para yakuake, en realidad le haces justicia a este gran emulador del terminal de KDE.

3ro: Podrias decirme como instalar el tema de yakuake, que por hay mismo si quieres creo un script y te lo paso o podrias crear un script para la instalación de estos paquetes.

gracias.

**Comment by mcder3** [comment]
1 y 2 muchas gracias y pues estamos tratando de hacr lo mejor posible :D 

3 Puedes descargarlo desde [KDE Store](https://store.kde.org/p/1191468/) y desde Aspecto le das a la opción Instalar una nueva piel para buscar el archivo que has descargado.

Por favor no crees un script, ya que me gustaría que las descargas se hagan por medio de KDE Store.

**Comment by DevDorrejo** [comment]
Hola, gracias por la respuesta.

Vi que todos tus temas estan en KDE store, soy usuario de openSUSE tumbleweed y cuando instalo los temas de escritorio o yakuake, se crea la carpeta y se pegan los archivos, pero al momento de cerrar la ventana de instalar extensiones se elimina la carpeta y me sale un mensaje, conoces alguna solución?

**Comment by CeCallejas** [comment]
Ese es un problema dentro de openSUSE, deberías de notificar el error en su lista de bugs.

**Comment by DevDorrejo** [comment]
Ok, gracias.

**Comment by mcder3** [comment]
Puedes instalarlo de forma manual, moviendo el contenido del archivo hacia la carpeta "/home/usuario/.local/share/yakuake/skins/"
